version: '3.7'

services:
  libreodysee:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreodysee
    hostname: libreodysee
    restart: always
    user: 65534:65534
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - '127.0.0.1:3245:3000'
    volumes:
      - ./data/config.yml:/app/config.yml
